### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by barsimark** [BME-MIT-IET/iet-hf-2022-iet_se_lattam_meg#1]
Configure CI pipeline with Github Actions

**Comment by barsimark** [comment]
A main branchen csináltam meg, mert a workflow úgyis ott fut.

Majd ki kell bővíteni a pom.xml és a maven.yml fájlt ha lesznek Unit testek illetve SonarCloud.

**Comment by akapush** [comment]
Kezdésnek ez jó szerintem is, köszi
